site_name: Link User Guide
repo_url: https://github.com/dyalog/link
repo_name: Dyalog/Link
nav:
  - Overview:
    - index.md
    - Discussion/TechDetails.md
    - Discussion/Workspaces.md
    - Discussion/History.md
    
  - Install and Upgrade:
    - Usage/Installation.md
    - Upgradeto30.md
    - ChangeHistory.md
    
  - Working with Link:
    - Usage/index.md
    - Usage/Setup.md
    - Usage/WStoLink.md
    - Usage/SALTtoLink.md
    
  - API & Command Reference:
    - API/index.md
    - API/Link.Add.md
    - API/Link.Break.md
    - API/Link.CaseCode.md
    - API/Link.Create.md
    - API/Link.Export.md
    - API/Link.Expunge.md
    - API/Link.Fix.md
    - API/Link.GetFileName.md
    - API/Link.GetItemName.md
    - API/Link.Import.md
    - API/Link.LaunchDir.md
    - API/Link.Notify.md
    - API/Link.Refresh.md
    - API/Link.Resync.md
    - API/Link.Status.md
    - API/Link.StripCaseCode.md
    - API/Link.TypeExtension.md
    - API/Link.Version.md
    
theme:
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - navigation.sections
    - navigation.instant
  name: material

extra_css:
  - style/main.css

plugins:
  - search

markdown_extensions:
  - admonition
  - abbr